/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import dao.CaLamViecDao;
import dao.NhanVienDAO;
import entity.CaLamViec;
import entity.NhanVien;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import utils.JdbcHelper;
import utils.MsgBox;

/**
 *
 * @author PC
 */
public class QuanlyCaLamViec extends javax.swing.JDialog {
    CaLamViecDao clvdao = new CaLamViecDao();
    NhanVienDAO nvdao = new NhanVienDAO();
    int row = -1;

    /**
     * Creates new form QuanlyCaLamViec
     */
    public QuanlyCaLamViec(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    public void init() {
        setLocationRelativeTo(this);
        this.filltable();
        setTitle("Ca Làm Việc");
        this.updateStatus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnTong = new javax.swing.JPanel();
        jpnDanhMuc = new javax.swing.JPanel();
        btnHoaDon = new javax.swing.JButton();
        btnViTri = new javax.swing.JButton();
        btnChucVu = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnKho = new javax.swing.JButton();
        btnDoUong = new javax.swing.JButton();
        btnNhapHang = new javax.swing.JButton();
        jpnQuanLyTacVu = new javax.swing.JPanel();
        jpnQuanLyCaLamViec = new javax.swing.JPanel();
        lblMaNV = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        lblKhuVuc = new javax.swing.JLabel();
        cboBuoiLamViec = new javax.swing.JComboBox<>();
        lblBuoiLamViec = new javax.swing.JLabel();
        btnFirst = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        txtKhuVuc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        lblQuanLyCaLamViec = new javax.swing.JLabel();
        jpnBangKhuVuc = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhuVuc = new javax.swing.JTable();
        jpnTimKiem = new javax.swing.JPanel();
        lblBuoiLamViecTK = new javax.swing.JLabel();
        lblKhuVucTK = new javax.swing.JLabel();
        txtKhuVucTK = new javax.swing.JTextField();
        cboBuoiLamViecTK = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();
        lblTimKiem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpnTong.setBackground(new java.awt.Color(153, 255, 153));

        jpnDanhMuc.setBackground(new java.awt.Color(204, 255, 204));
        jpnDanhMuc.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Quản lý Chức Năng\n\n", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 17))); // NOI18N
        jpnDanhMuc.setName(""); // NOI18N

        btnHoaDon.setText("HÓA ĐƠN");
        btnHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnViTri.setText("CA LÀM VIỆC");
        btnViTri.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnChucVu.setText("CHỨC VỤ ");
        btnChucVu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnNhanVien.setText("NHÂN VIÊN ");
        btnNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnThongKe.setText("THỐNG KÊ");
        btnThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnKho.setText("KHO");
        btnKho.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnDoUong.setText("ĐỒ UỐNG");
        btnDoUong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnNhapHang.setText("NHẬP HÀNG");
        btnNhapHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jpnDanhMucLayout = new javax.swing.GroupLayout(jpnDanhMuc);
        jpnDanhMuc.setLayout(jpnDanhMucLayout);
        jpnDanhMucLayout.setHorizontalGroup(
            jpnDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDanhMucLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDoUong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(btnKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViTri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnDanhMucLayout.setVerticalGroup(
            jpnDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDanhMucLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViTri, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKho, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnQuanLyTacVu.setBackground(new java.awt.Color(204, 255, 204));
        jpnQuanLyTacVu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Quản lý tác vụ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jpnQuanLyCaLamViec.setBackground(new java.awt.Color(153, 255, 153));
        jpnQuanLyCaLamViec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMaNV.setText("Mã NV:");

        lblKhuVuc.setText("Tên Nhân Viên:");

        cboBuoiLamViec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sáng", "Trưa", "Tối", " " }));

        lblBuoiLamViec.setText("Buổi làm việc:");

        btnFirst.setText("<<");
        btnFirst.setEnabled(false);
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        jLabel5.setText("Khu Vực:");

        btnPrev.setText("|<");
        btnPrev.setEnabled(false);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setText(">|");
        btnNext.setEnabled(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText(">>");
        btnLast.setEnabled(false);
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnQuanLyCaLamViecLayout = new javax.swing.GroupLayout(jpnQuanLyCaLamViec);
        jpnQuanLyCaLamViec.setLayout(jpnQuanLyCaLamViecLayout);
        jpnQuanLyCaLamViecLayout.setHorizontalGroup(
            jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQuanLyCaLamViecLayout.createSequentialGroup()
                        .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnQuanLyCaLamViecLayout.createSequentialGroup()
                                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnQuanLyCaLamViecLayout.createSequentialGroup()
                                        .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMaNV)
                                            .addComponent(lblKhuVuc))
                                        .addGap(7, 7, 7)
                                        .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnQuanLyCaLamViecLayout.createSequentialGroup()
                                        .addComponent(lblBuoiLamViec)
                                        .addGap(12, 12, 12)
                                        .addComponent(cboBuoiLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                                .addComponent(btnFirst)
                                .addGap(37, 37, 37)
                                .addComponent(btnPrev))
                            .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSua)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNext, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(54, 54, 54)
                        .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMoi)
                            .addComponent(btnLast))
                        .addGap(45, 45, 45))))
        );
        jpnQuanLyCaLamViecLayout.setVerticalGroup(
            jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNV)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKhuVuc)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboBuoiLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuoiLamViec))
                .addGap(23, 23, 23)
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst)
                    .addComponent(btnPrev)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addGap(12, 12, 12)
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnMoi)
                    .addComponent(btnXoa))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        lblQuanLyCaLamViec.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblQuanLyCaLamViec.setText("Quản lý ca làm việc");

        jpnBangKhuVuc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblKhuVuc.setBackground(new java.awt.Color(204, 255, 204));
        tblKhuVuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ NV", "TÊN NV", "KHU VỰC", "BUỔI LÀM VIỆC"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhuVuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhuVucMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhuVuc);

        javax.swing.GroupLayout jpnBangKhuVucLayout = new javax.swing.GroupLayout(jpnBangKhuVuc);
        jpnBangKhuVuc.setLayout(jpnBangKhuVucLayout);
        jpnBangKhuVucLayout.setHorizontalGroup(
            jpnBangKhuVucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBangKhuVucLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnBangKhuVucLayout.setVerticalGroup(
            jpnBangKhuVucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jpnTimKiem.setBackground(new java.awt.Color(153, 255, 153));
        jpnTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblBuoiLamViecTK.setText("Buổi làm việc:");

        lblKhuVucTK.setText("Tìm kiếm:");

        txtKhuVucTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhuVucTKActionPerformed(evt);
            }
        });
        txtKhuVucTK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKhuVucTKKeyReleased(evt);
            }
        });

        cboBuoiLamViecTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sáng", "Trưa", "Tối" }));
        cboBuoiLamViecTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboBuoiLamViecTKActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnTimKiemLayout = new javax.swing.GroupLayout(jpnTimKiem);
        jpnTimKiem.setLayout(jpnTimKiemLayout);
        jpnTimKiemLayout.setHorizontalGroup(
            jpnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnTimKiemLayout.createSequentialGroup()
                        .addGroup(jpnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpnTimKiemLayout.createSequentialGroup()
                                .addComponent(lblBuoiLamViecTK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboBuoiLamViecTK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jpnTimKiemLayout.createSequentialGroup()
                                .addComponent(lblKhuVucTK)
                                .addGap(36, 36, 36)
                                .addComponent(txtKhuVucTK, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnTimKiemLayout.setVerticalGroup(
            jpnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTimKiemLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jpnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuoiLamViecTK)
                    .addComponent(cboBuoiLamViecTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKhuVucTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKhuVucTK))
                .addGap(18, 18, 18)
                .addComponent(btnTimKiem)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        lblTimKiem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTimKiem.setText("Tìm kiếm Thông Tin ");

        javax.swing.GroupLayout jpnQuanLyTacVuLayout = new javax.swing.GroupLayout(jpnQuanLyTacVu);
        jpnQuanLyTacVu.setLayout(jpnQuanLyTacVuLayout);
        jpnQuanLyTacVuLayout.setHorizontalGroup(
            jpnQuanLyTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyTacVuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnQuanLyTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnQuanLyTacVuLayout.createSequentialGroup()
                        .addGroup(jpnQuanLyTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTimKiem)
                            .addComponent(jpnQuanLyCaLamViec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jpnBangKhuVuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpnQuanLyTacVuLayout.createSequentialGroup()
                        .addComponent(lblQuanLyCaLamViec)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnQuanLyTacVuLayout.setVerticalGroup(
            jpnQuanLyTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyTacVuLayout.createSequentialGroup()
                .addComponent(lblQuanLyCaLamViec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnQuanLyTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnQuanLyTacVuLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jpnQuanLyCaLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jpnBangKhuVuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jpnTongLayout = new javax.swing.GroupLayout(jpnTong);
        jpnTong.setLayout(jpnTongLayout);
        jpnTongLayout.setHorizontalGroup(
            jpnTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnQuanLyTacVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnTongLayout.setVerticalGroup(
            jpnTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnQuanLyTacVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnTongLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jpnDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        find();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void cboBuoiLamViecTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboBuoiLamViecTKActionPerformed
        // TODO add your handling code here:
        findCBO();
    }//GEN-LAST:event_cboBuoiLamViecTKActionPerformed

    private void txtKhuVucTKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKhuVucTKKeyReleased
        // TODO add your handling code here:
        find();
    }//GEN-LAST:event_txtKhuVucTKKeyReleased

    private void tblKhuVucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhuVucMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tblKhuVuc.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblKhuVucMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void txtKhuVucTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhuVucTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKhuVucTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanlyCaLamViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanlyCaLamViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanlyCaLamViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanlyCaLamViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanlyCaLamViec dialog = new QuanlyCaLamViec(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChucVu;
    private javax.swing.JButton btnDoUong;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKho;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnNhapHang;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnViTri;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboBuoiLamViec;
    private javax.swing.JComboBox<String> cboBuoiLamViecTK;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnBangKhuVuc;
    private javax.swing.JPanel jpnDanhMuc;
    private javax.swing.JPanel jpnQuanLyCaLamViec;
    private javax.swing.JPanel jpnQuanLyTacVu;
    private javax.swing.JPanel jpnTimKiem;
    private javax.swing.JPanel jpnTong;
    private javax.swing.JLabel lblBuoiLamViec;
    private javax.swing.JLabel lblBuoiLamViecTK;
    private javax.swing.JLabel lblKhuVuc;
    private javax.swing.JLabel lblKhuVucTK;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblQuanLyCaLamViec;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JTable tblKhuVuc;
    private javax.swing.JTextField txtKhuVuc;
    private javax.swing.JTextField txtKhuVucTK;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
    void filltable() {
        DefaultTableModel model = (DefaultTableModel) tblKhuVuc.getModel();
        model.setRowCount(0);
        try {
            List<CaLamViec> list = new CaLamViecDao().selectAll();
            for (CaLamViec clv : list) {
                Object[] row = {
                    clv.getMaNV(),
                    clv.getTenNV(),
                    clv.getKhuVuc(),
                    clv.getMaCLV()};
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn");
        }
    }

    void setForm(CaLamViec clv) {

        txtMaNV.setText(clv.getMaNV());
        txtTenNV.setText(clv.getTenNV());
        txtKhuVuc.setText(clv.getKhuVuc());
        String buoiLamViecValue = clv.getMaCLV();
        if (buoiLamViecValue.equals("CLV001")) {
            cboBuoiLamViec.setSelectedItem("Sáng");
        } else if (buoiLamViecValue.equals("CLV002")) {
            cboBuoiLamViec.setSelectedItem("Trưa");
        } else if (buoiLamViecValue.equals("CLV003")) {
            cboBuoiLamViec.setSelectedItem("Tối");
        }             
        cboBuoiLamViec.setSelectedItem(buoiLamViecValue);        
    }
    
    CaLamViec getForm() {
        CaLamViec clv = new CaLamViec();
        clv.setMaNV(txtMaNV.getText());
        clv.setTenNV(txtTenNV.getText());
        clv.setKhuVuc(txtKhuVuc.getText());

        String selectedBuoiLamViec = cboBuoiLamViec.getSelectedItem()+"";
        String buoiLamViecValue = "";

        switch (selectedBuoiLamViec) {
            case "Sáng":
                buoiLamViecValue = "CLV001";
                break;
            case "Trưa":
                buoiLamViecValue = "CLV002";
                break;
            case "Tối":
                buoiLamViecValue = "CLV003";
                break;
            default:
                break;
        }
        clv.setMaCLV(buoiLamViecValue);
        return clv;
    }


    void clearForm() {
        txtMaNV.setText("");
        txtTenNV.setText("");
        txtKhuVuc.setText("");
        DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) cboBuoiLamViec.getModel();
        model.setSelectedItem("Sáng");        
        this.row = -1;
        this.updateStatus();
    }

    void edit() {
        if (this.row >= 0 && this.row < tblKhuVuc.getRowCount()) {
            String maNV = (String) tblKhuVuc.getValueAt(this.row, 0);
            String maCLV = (String) tblKhuVuc.getValueAt(this.row, 3);
            CaLamViec clv1 = new CaLamViecDao().selectByMaNVandMaCLV(maNV,maCLV);
            this.setForm(clv1);
            tblKhuVuc.setRowSelectionInterval(this.row, this.row);
            this.updateStatus();
        }
    }

    private void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblKhuVuc.getRowCount() - 1);
        //trạng thái form
        txtMaNV.setEditable(edit);
        btnFirst.setEnabled(edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);
        //trạng thái điều hướng
        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);
    }

    void first() {
        this.row = 0;
        this.edit();
    }

    void last() {
        this.row = tblKhuVuc.getRowCount() - 1;
        this.edit();
    }

    void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    void next() {
        if (this.row < tblKhuVuc.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }

    void insert() {
        if (check()) {
        CaLamViec clv = getForm();
        try {
            new CaLamViecDao().insert(clv);
            this.filltable();
            MsgBox.alert(this, "Thêm mới thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại");
        }
// Chỉ Thêm được ca Làm việc mới 
        }
    }
    
    void update() {
        if (check()) {
            CaLamViec clv = getForm();
                try {
                    new CaLamViecDao().updateS(clv);
                    this.filltable();
                    MsgBox.alert(this, "Cập nhật thành công");
                } catch (Exception e) {
                    MsgBox.alert(this, "Cập nhật thất bại");
                }
        }
    }
    
    void delete() {
        if (this.row >= 0 && this.row < tblKhuVuc.getRowCount()) {
            String maNV = (String) tblKhuVuc.getValueAt(this.row, 0);
            String maCLV = (String) tblKhuVuc.getValueAt(this.row, 3);
            if (MsgBox.confirm(this, "Bạn có muốn xóa Ca Làm việc này này?")) {
                try {
                    new CaLamViecDao().deleteMaNVandMaCLV(maNV, maCLV);
                    this.filltable();
                    this.clearForm();
                    MsgBox.alert(this, "Xóa thành công");
                } catch (Exception e) {
                    MsgBox.alert(this, "Xóa thất bại");
                }
            }
        }
    }
    
    void fillTableFind() {
        DefaultTableModel model = (DefaultTableModel) tblKhuVuc.getModel();
        model.setRowCount(0);
        try {
            String keyword = txtKhuVucTK.getText();
            List<CaLamViec> list = new CaLamViecDao().selectByKeyword(keyword);
            for (CaLamViec clv : list) {
                    if (clv != null) {
                        Object[] row = {
                            clv.getMaNV(),
                            clv.getTenNV(),
                            clv.getKhuVuc(),
                            clv.getMaCLV()};
                        model.addRow(row);
                    }
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn");
        }
    }
    
    void findCBOX(){
        DefaultTableModel model = (DefaultTableModel) tblKhuVuc.getModel();
        model.setRowCount(0);
        try {
            String keyword = cboBuoiLamViecTK.getSelectedItem()+"";
            String buoiLamViecValue = "";
        switch (keyword) {
            case "Sáng":
                buoiLamViecValue = "CLV001";
                break;
            case "Trưa":
                buoiLamViecValue = "CLV002";
                break;
            case "Tối":
                buoiLamViecValue = "CLV003";
                break;
            default:
                break;
        }
            List<CaLamViec> list1 = new CaLamViecDao().selectByKeywordCBO(buoiLamViecValue);
            for (CaLamViec clv : list1) {
                    if (clv != null) {
                        Object[] row = {
                            clv.getMaNV(),
                            clv.getTenNV(),
                            clv.getKhuVuc(),
                            clv.getMaCLV()};
                        model.addRow(row);
                    }
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn");
        }
    }
    boolean check() {
        boolean hasError = false;
        if (txtMaNV.getText().isEmpty()&&txtTenNV.getText().isEmpty()&&txtKhuVuc.getText().isEmpty()) {
            MsgBox.alert(this, "Bạn chưa nhập thông tin Nhân Viên");
            hasError = true;
        }
        else if (txtTenNV.getText().isEmpty()&&txtKhuVuc.getText().isEmpty()) {
            MsgBox.alert(this, "Bạn chưa nhập Tên và Khu vực của Nhân Viên");
            hasError = true;
        }
        else if (txtMaNV.getText().isEmpty()&&txtTenNV.getText().isEmpty()) {
            MsgBox.alert(this, "Bạn chưa nhập Mã và Tên Nhân Viên");
            hasError = true;
        }
        else if (txtMaNV.getText().isEmpty()&&txtKhuVuc.getText().isEmpty()) {
            MsgBox.alert(this, "Bạn chưa nhập Mã và khu vực Nhân Viên");
            hasError = true;
        }
        else if (txtMaNV.getText().isEmpty()) {
            MsgBox.alert(this, "Bạn chưa nhập Mã Nhân Viên");
            hasError = true;
        }
        else if (txtTenNV.getText().isEmpty()) {
            MsgBox.alert(this, "Bạn chưa nhập Tên Nhân Viên\n");
            hasError = true;
        }
        else if (txtKhuVuc.getText().isEmpty()) {
            MsgBox.alert(this, "Bạn chưa nhập khu vực\n");
            hasError = true;
        }
        return !hasError;
    }

    void find() {
        this.fillTableFind();
        this.clearForm();
        this.row = -1;
        this.updateStatus();
    }
    void findCBO() {
        this.findCBOX();
        this.clearForm();
        this.row = -1;
        this.updateStatus();
    }

}
